#ifndef ULT_FORK_PRIV_H
# define ULT_FORK_PRIV_H

#ifdef __FUT_H_INSIDE__
# error "Do not include this file directly. Use <ft_ultimate_tester.h> instead."
#endif

# include "timeout_priv.h"
# include "error_pub.h"
# include <sys/types.h>

typedef t_error (*t_parent_runner)(pid_t child_pid, void *data);
typedef t_error (*t_child_runner)(void *data);

typedef struct s_fork_context
{
	size_t			timeout;
	t_parent_runner	parent_runner;
	t_child_runner	child_runner;
	void			*data;
	pid_t			child_pid;		// Generated by process_fork()
	int				result_pipe[2];	// Generated by process_fork()
}	t_fork_context;

t_error process_fork(t_fork_context *context);

#endif
