#ifndef ULT_ERROR_PUB_H
# define ULT_ERROR_PUB_H

# include "print_pub.h"

static const char *names[] =
{
	"NO_ERROR",
	"SECTION_CORRUPTED",
	"RESULT_PIPE_CREATION_FAILED",
	"SYNC_PIPE_CREATION_FAILED",
	"SYNC_PIPE_READ_FAILED",
	"FORK_FAILED",
	"ALARM_SET_FAILED",
	"ALARM_CANCEL_FAILED",
	"REDIRECT_START_FAILED"
};

typedef enum e_error
{
	NO_ERROR,
	SECTION_CORRUPTED,
	RESULT_PIPE_CREATION_FAILED,
	SYNC_PIPE_CREATION_FAILED,
	SYNC_PIPE_READ_FAILED,
	FORK_FAILED,
	ALARM_SET_FAILED,
	ALARM_CANCEL_FAILED,
	REDIRECT_START_FAILED
}	t_error;

void	ult_print_err_priv(t_error err);

#endif
