#ifndef LIB_ULTIMATE_TESTER_TYPES_H
# define LIB_ULTIMATE_TESTER_TYPES_H

# include <stddef.h>
# include <stdint.h>
# include <stdbool.h>
# include "redirect.h"

enum Set_types
{
	COMPARE_OUTPUTS,	// Only compare the outputs
	COMPARE_RETURNS,	// Only compare the returned values
	COMPARE_BOTH		// Compare both the ouptuts and the returned values
};

enum Status
{
	QUEUED,
	RUNNING,
	PASSED,
	FAILED,
	TIMED_OUT,
	CRASHED
};

typedef struct s_try
{
	enum Status	status;		// default: QUEUED
	char		*args;		// Args with wich tested function should be called (e.g. "arg1, arg2, "arg3", arg4")
}	t_try;

typedef struct s_function
{
	int 		(*fn)(const char *, ...);	// Pointer to function
	char		*out;		// Catched from redirected stdout
	intptr_t	ret;		// Return value (universal type for all int and pointers)
} t_function;

typedef struct s_set
{
	const char		*name;		// User choosen name
	enum Set_types	type;		// COMPARE_OUTPUTS / COMPARE_RETURNS / COMPARE_BOTH
	enum Status		status;		// default: QUEUED
	size_t			timeout;	// Max duration before auto timeout (sec)
	int 			(*fn1)(const char *, ...);	// First function to compare
	int 			(*fn2)(const char *, ...);	// Second function to compare
	// void			(*fn1)();	// First function to compare
	// void			(*fn2)();	// Second function to compare
	void			(*runner)();// Auto-generated by the Compare() macro 
}	t_set;

typedef struct s_test
{
	t_set			*set;
	enum Set_types	type;
	enum Status		status;
	size_t			timeout;
	t_redirect		fake_stdout;
	t_function		fn1;
	t_function		fn2;
}	t_test;

typedef struct s_run
{
	enum Status	status;
	long		total;
	long		passed;
	long		failed;
	long		timed_out;
	long		crashed;
}	t_run;

#endif
