#ifndef ULT_TYPES_H
# define ULT_TYPES_H

# include <stddef.h>
# include <stdint.h>
# include <stdbool.h>
# include <sys/types.h>

typedef enum e_set_types
{
	C_OUTPUTS,
	C_RETURNS,
	C_BOTH
}	t_set_type;

typedef enum e_status
{
	QUEUED,
	RUNNING,
	PASSED,
	FAILED,
	TIMED_OUT,
	CRASHED
}	t_status;

typedef struct s_string
{
	char	*data;
	size_t	len;
}	t_string;

typedef struct s_try
{
	t_status	status;		// default: QUEUED
	char		*args;		// Args with wich tested function should be called (e.g. "arg1, arg2, "arg3", arg4")
}	t_try;

typedef struct s_function
{
	int 		(*fn)(const char *, ...);	// Pointer to function
	char		*out;		// Catched from redirected stdout
	intptr_t	ret;		// Return value (universal type for all int and pointers)
} t_function;

typedef struct s_set
{
	const char		*name;		// User choosen name
	t_set_type		type;		// COMPARE_OUTPUTS / COMPARE_RETURNS / COMPARE_BOTH
	t_status		status;		// default: QUEUED
	size_t			timeout;	// Max duration before auto timeout (sec)
	int 			(*fn1)(const char *, ...);	// First function to compare
	int 			(*fn2)(const char *, ...);	// Second function to compare
	// void			(*fn1)();	// First function to compare
	// void			(*fn2)();	// Second function to compare
	void			(*runner)();// Auto-generated by the Compare() macro 
}	t_set;

typedef struct s_test
{
	t_set			*set;
	t_set_type		type;
	t_status		status;
	size_t			timeout;
	t_function		fn1;
	t_function		fn2;
}	t_test;

typedef struct s_run
{
	t_status	status;
	long		total;
	long		passed;
	long		failed;
	long		timed_out;
	long		crashed;
}	t_run;

#endif
